# The name of this app. Must be unique within a project.
name: socket
type: 'nodejs:14'
build:
  flavor: none
dependencies:
  nodejs:
    yarn: "*"
web:
  upstream:
    socket_family: tcp
    protocol: http
  commands:
    start: node socket.js
  locations:
    '/':
      passthru: true
