"https://www.{default}/":
  type: upstream
  upstream: "app:http"

"https://{default}/":
  type: redirect
  to: "https://www.{default}/"

# "https://{default}/ws":
#   type: upstream
#   upstream: "socket:http"
#   cache:
#     enabled: false
