"https://www.{default}/":
  type: upstream
  upstream: "app:http"

"https://{default}/":
  type: redirect
  to: "https://www.{default}/"

"https://backend.{default}/":
  type: upstream
  upstream: "socket:http"
  cache:
    enabled: false
