"https://www.{default}/":
  type: upstream
  upstream: "app:http"

"https://{default}/":
  type: redirect
<<<<<<< Updated upstream
  to: "https://www.{default}/"
=======
  to: "https://www.{default}/"

"https://backend.{default}/":
    type: upstream
    upstream: "drupal:http"
>>>>>>> Stashed changes
